title:              Wei Cheng
email:              chengwei0815@gmail.com
description:        Data Analyst / Data Scientist
author:             Wei Cheng
baseurl:            ""
url:                "https://chengwei0815.github.io"

# Social Profiles
twitter_username:   
github_username:   chengwei0815
facebook_username:  
instagram_username:  
linkedin_username:  weicheng611

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
kramdown:
input: GFM
syntax_highlighter: rouge
